#
# ~/.bashrc
#

#set starship
#
eval "$(starship init bash)"


# If not running interactively, don't do anything
[[ $- != *i* ]] && return

alias ls='lsd'
alias grep='grep --color=auto'
alias kimg='kitty +kitten icat'
alias neofetch='neofetch --kitty ~/.config/neofetch/arch.png --size 250px'

PS1='[\u@\h \W]\$ '
. "$HOME/.cargo/env"
