#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
sxhkd & 
xrandr --output HDMI-0 --primary --mode 1920x1080 --pos 1080x522 --rotate normal --output DP-0 --off --output DP-1 --off --output HDMI-1 --mode 1920x1080 --pos 0x0 --rotate left --output DP-2 --off --output DP-3 --off &
xwallpaper --screen 0 --zoom ~/.wallpaper/waves.png & 
picom -b &
eww open-many bar
setxkbmap de &

bspc monitor -d 1 2 3 4


bspc config pointer_follows_focus true
bspc config pointer_follows_monitor true
bspc config border_width         3
bspc config window_gap          25
bspc config split_ratio          0.52
bspc config borderless_monocle   false
bspc config gapless_monocle      false
bspc config focused_border_color "#BBDFD9"
bspc config normal_border_color  "#565A6E"
bspc config active_border_color  "#000000"


bspc rule -a Pcmanfm state=floating, width=600, height=600
